#ifndef __USR_ERROR_H__
#define __USR_ERROR_H__
typedef enum TAG_ENUM_USR_ERROR_CODE
{
    USR_ERROR_CODE_SORTF_OPTION_ERROR = 0,

    USR_ERROR_CODE_MAX = USER_DEFINE_ERROR_CODE_MAX,
}ENUM_USR_ERROR_CODE;

#endif
